### PR TITLE
Added Message menus / Fix CI

### LINKED ISSUE #12: Support Message Menus
Recently Mattermost added message menus to interactive buttons. 
See [link](https://docs.mattermost.com/developer/interactive-messages.html#message-menus).

Will work on it this weekend.

### LINKED ISSUE #16: Appveyor PR builds failing
I've clearly set something up wrong in the Appveyor config. Builds for tags work with no issue, and branch builds appear to work.

It appears to relate to the AssemblyInfo

```text
obj\Release\net452\Matterhook.NET.MatterhookClient.AssemblyInfo.cs(18,59): warning CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [C:\projects\matterhook-net-matterhookclient\Matterhook.NET.MatterhookClient\Matterhook.NET.MatterhookClient.csproj]
obj\Release\net452\Matterhook.NET.MatterhookClient.AssemblyInfo.cs(22,55): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [C:\projects\matterhook-net-matterhookclient\Matterhook.NET.MatterhookClient\Matterhook.NET.MatterhookClient.csproj]
```

### PR DESCRIPTION
**Pull request by rgomez90**
Closes #12 
Closes #16 

See [Mattermost Docs ](https://docs.mattermost.com/developer/interactive-messages.html#message-buttons) about Message menus

Just need to update README, but have a question about it. 
@PromoFaux do you think for the advanced Mattermost message example, we could create one message with all availabe options (button, menu, usersMenu, channelsMenus, Field) like this?
image

Just to avoid repeting code and having a huge README. We could give more examples in the wiki or sth...

### CODE REVIEW

**Comment by rgomez90** [comment]
So I finished implementing Message menus and also fixed CI. After @PromoFaux review we should be ready to merge development and to release **v1.4**.

**Comment by PromoFaux** [comment]
SO, just to confirm, we need to up the version number in the appveyor yaml file on release, right? I was initially doing it by tag reference, but whatever works!

**Comment by PromoFaux** [comment]
RE: Readme, pop an example for message menus in at the bottom for now.. and then we can have an overhaul of the Readme in a separate PR to keep things tidy.

**Comment by rgomez90** [comment]
> SO, just to confirm, we need to up the version number in the appveyor yaml file on release, right? I was initially doing it by tag reference, but whatever works!

For now, appveyor.yml works as follow:

Hard coded version in appveyor.yml env variable VERSION => now is 1.3

* if tag commit then version will be tag (i.e. 1.4)
* it not tag commit but master commit => will be {VERSION}.{BuildNr} i.e. 1.3.45
* if not tag but development => {VERSION}.{BuildNr}-dev

assembly version attribute will always be {VERSION} to avoid binding redirects (afaik).

So for next release we just need to create the tag 1.4 and then update VERSION env. variable to 1.4, that's all.

Take a look at appveyor.yaml and build console for better understanding 😄

**Comment by rgomez90** [comment]
> RE: Readme, pop an example for message menus in at the bottom for now.. and then we can have an overhaul of the Readme in a separate PR to keep things tidy.

Will do it this afternoon

**Comment by PromoFaux** [comment]
>So for next release we just need to create the tag 1.4 and then update VERSION env. variable to 1.4, that's all

I think probably that should be the other way around. Change the env variable to 1.4 and _then_ create the tag. Else it will get built with 1.3 :)

**Comment by rgomez90** [comment]
> > So for next release we just need to create the tag 1.4 and then update VERSION env. variable to 1.4, that's all
> 
> I think probably that should be the other way around. Change the env variable to 1.4 and _then_ create the tag. Else it will get built with 1.3 :)

The appveyor.yml checks if the commit was a tag and USES THE TAG NAME without using any env. variable.

If the commit was NOT A TAG then it uses the env. variable to calculate the version. 
Here a portion of the file, check `init part`, there is where the "magic" happens. 

```yaml
branches:
  only:
    - master
    - development

environment:
  VERSION: 1.3

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration: Release

init:
  - cmd: echo %APPVEYOR_REPO_TAG%
  - cmd: set BUILD_VERSION=%VERSION%.%APPVEYOR_BUILD_NUMBER% #1.3.40
  - cmd: IF %APPVEYOR_REPO_TAG% == "true" (set PROJECT_VERSION=%APPVEYOR_REPO_TAG_NAME%) ELSE (IF {branch}=="master" (set PROJECT_VERSION=%BUILD_VERSION%) ELSE set PROJECT_VERSION=%BUILD_VERSION%-dev) 
  - cmd: echo %PROJECT_VERSION%
  - cmd: echo %APPVEYOR_BUILD_NUMBER%
  - cmd: echo %APPVEYOR_BUILD_VERSION%
  - cmd: echo %APPVEYOR_REPO_TAG_NAME%

install:
  appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

dotnet_csproj:  
  patch: true
  file: '**\*.csproj'
  version: $(PROJECT_VERSION)
  assembly_version: $(VERSION)
  file_version: $(BUILD_VERSION)
  informational_version: $(PROJECT_VERSION)
```
We can change the configuration but in my commit this is how I configure it.

**Comment by PromoFaux** [comment]
Right-oh. Internet a bit spotty at the moment, but will check out your changes ASAP.

Cheers!

**Comment by PromoFaux** [comment]
LGTM

**Pull request merged**
