### PR TITLE
V1.4 release

### PR DESCRIPTION
**Pull request by PromoFaux**

### CODE REVIEW

**Review by rgomez90 — DISMISSED** [review]

**Review by rgomez90 — DISMISSED** [review]

**Comment by rgomez90** [comment]
@PromoFaux I added the examples, cleaned code & merged ManualTests into dev (#17). 

I think we are ready for release v1.4 😄

Next step SHOULD BE to write tests. Imho we should not move on without having a tested codebase. 

### EDIT:  PLEASE MERGE #18 before merging this PR.

**Comment by PromoFaux** [comment]
>I think we are ready for release v1.4 😄

LGTM, just want to run through some final sanity checks before doing so though..! Will try and get to it on my lunch break today

**Comment by PromoFaux** [comment]
OH WAIT. I've missed something very important.

**Comment by PromoFaux** [comment]
Something interesting to note (shouldn't affect anything at the moment as I'm yet to tag the release)

Although appveyor has just built the `master` branch, it still included `-dev` in the version number...

image

**Pull request merged**
